spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/Boekhoud
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto = create-drop

jwt.secret=BoekhoudDrerries69420
jwt.expiration=3600000